### ISSUE TITLE
Not available for typescript  

### ISSUE THREAD

**Issue by pravinjadhav7** [MGrin/mgr-pdf-viewer-react#12]
![image](https://user-images.githubusercontent.com/24220012/65577669-e19e2300-df91-11e9-9b0c-bb7a341c05db.png)

**Comment by MGrin** [comment]
`pdf-viewer-reactjs` is another package, `mgr-pdf-viewer-react` is based on it.

Also there are no plans to add types for this package. You can use it in TS excluding from type checking
