### ISSUE TITLE
will this module be able to load pdf on Mozilla firefox ? 

### ISSUE THREAD

**Issue by tkssharma** [MGrin/mgr-pdf-viewer-react#13]
I am not able to get pdf on Firefox and how to set height width of pdf viewer

**Comment by MGrin** [comment]
Firefox - any errors? Versions? I didn't have any problems with firefox, can you provide more info please?

Width and Height - you should set it on the wrapping component + use the scale prop

**Comment by MGrin** [comment]
Closing it due to missing info
