### ISSUE TITLE
Unable to access a pdf from public folder of create-react-app

### ISSUE THREAD

**Issue by SupreethBaliga** [MGrin/mgr-pdf-viewer-react#14]
Is there any way we can open a pdf present in the public folder of create-react-app created directory structure? There's nothing mentioned in the documentation about it.

**Comment by MGrin** [comment]
I see you closed it, but the idea here is to use base64 instead of the path to file

**Comment by SupreethBaliga** [comment]
Yeah. That works properly. Thanks.
