### ISSUE TITLE
Headers are not included in request

### ISSUE THREAD

**Issue by esercankutay** [MGrin/mgr-pdf-viewer-react#15]
I have to use token to get file like below. But when i inspect the request i see that url is corect but token i gave isnt included. Are headers even supported or we just have to settle with url?
`<PDFViewer document={{
        url: process.env.API_AUTHENTICATION + 'downloadpdf',
            httpHeaders: {  
         'Authorization': 'Bearer ' + getCookie('token'),
            },
withCredentials: true,
        }} />`

**Comment by MGrin** [comment]
The document prop has a connection field, you can try that one and add some headers in there. Also, to see what are the possible options of the document object you can refer to the react-pdf-js documentation (but carefully, refer to the version that is used in this package, not the latest one!)

**Comment by esercankutay** [comment]
Thanks. Along with some help that worked flawlessly. Here's the code that works:
<PDFViewer document={{
                            connection: {
                                url: process.env.API_AUTHENTICATION + 'downloadpdf',
                            httpHeaders: {
                                'Authorization': 'Bearer ' + getCookie('token'),
                            },
                            withCredentials: true,
                            }
                        }} />

**Comment by MGrin** [comment]
Cool! I'll add it in the docs, thanks for using!
