### ISSUE TITLE
How to make the page view shrink?

### ISSUE THREAD

**Issue by rchancey** [MGrin/mgr-pdf-viewer-react#16]
Trying to run this on responsive mobile and can't figure how to make the actual page shrink. I can get the viewer to shrink but the page is still like 1000px wide.
is there a way to make the page shrink so it is like 95% of the container width?

**Comment by MGrin** [comment]
The only way of doing this would be to have a listener onRisize and change the scale prop dynamically.
Unfortunatelly there is no way of changing width and height of the pdf itself, only the scale prop
