### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jmsmhny** [MGrin/mgr-pdf-viewer-react#2]
After npm install mgr-pdf-viewer-react --save

Module not found: Can't resolve './Navigation' in '.../node_modules/mgr-pdf-viewer-react'

(Project made using crest-react-app.)

**Comment by MGrin** [comment]
My fault, gonna fix it today. Thank you!

**Comment by MGrin** [comment]
@jmsmhny fixed, current version is 0.0.3.
Please let me know if any other issues will occur.

👍
