### ISSUE TITLE
Zoom In - Out

### ISSUE THREAD

**Issue by gregorispielmann** [MGrin/mgr-pdf-viewer-react#27]
Hello!

Great react package. Thanks for that!

Is there any chance that include zoom (in and out) to the navigation?

Best regards!

**Comment by MGrin** [comment]
Hi!
Thanks for your question.
In the default navigation there is no zoom included, but you can easily implement it in your own navigation using the `scale` prop. What I mean by that you can take control over the scale outside of the pdf viewer into your component's state and modify it whenever you want.

Hope that helps!

**Comment by gregorispielmann** [comment]
Hello @MGrin thank you, I only customized the navigation bar, it's okay now. Thank you so much!
