### ISSUE TITLE
Download pdf feature

### ISSUE THREAD

**Issue by icecreamsandwich** [MGrin/mgr-pdf-viewer-react#45]
Is there a download pdf feature as we see when opening the pdf file in a browser? Thanks

![image](https://user-images.githubusercontent.com/3961511/103809797-0f708380-5080-11eb-946b-e1a87fd44ebf.png)

**Comment by MGrin** [comment]
Hi, no, there is no such a feature. You can implement it in your own component

**Comment by icecreamsandwich** [comment]
Okay @MGrin Thanks, Let me try that in our component itself.
