### ISSUE TITLE
Rotate pdf

### ISSUE THREAD

**Issue by FranciscoMateusVG** [MGrin/mgr-pdf-viewer-react#46]
Hi!
Is it possible to rotate the pdf ? Some files como upside down and i need to view them in the right position.

**Comment by MGrin** [comment]
Hi,
Unfortunately there is no such a way, and also I'm not sure the pdf-react package, on top of which this one is built, has this feature... Honestly I've never seen such a functionality in an embedded pdf viewers....
I think the best way to do so is to rotate the pdf on your backend and then return the new, rotated, version as base64 to your frontend and then render it...
