### ISSUE TITLE
Uable to render new file in the PDFViewer

### ISSUE THREAD

**Issue by shreyasb07** [MGrin/mgr-pdf-viewer-react#8]
Hi,
I'm trying to render different files in the PDFViewer, but however, it always shows the first selected file and does not update when other files are selected through the props!

This is how my component looks like: 
              

```
>  <PDFViewer
>                   document = {data.docInfo[0].docUrl}
>               />
```

and the render method for PDFViewer.js looks like

```
render() {
  const source = this.props.document;
  console.log('Source in render: ', source);
    const {
      loader,
      navigation,
      css,
    } = this.props;
    const {
      page,
      pages,
    } = this.state;
    const NavigationElement = navigation;
    const pdf = (
      <PDF
        file = {{url: source}}
         />

```
The value of the source changes each time i select a new file, but the Viewer always shows the old PDF file.

**Comment by MGrin** [comment]
Hi,
The document prop of PDFviewer should be an object with url field, while you are passing url directly. Try to change this and let me know if that works

Best,
Nikita

**Comment by shreyasb07** [comment]
Well by making the document prop of the PDFviewer to be an object with url field,
```
<PDFViewer
   document = {{ url: data.docInfo[0].docUrl}}
              />
```
I get an error in the console:  GET http://localhost:3001/[object%20Object] 404 (Not Found)

the const pdf console logs as given below:
```
pdf: $$typeof: Symbol(react.element)
key: null
props:
cMapPacked: false
cMapUrl: "../node_modules/pdfjs-dist/cmaps/"
file:
url: {url: "https://s3.us-east-2.amazonaws.com/mobimed-data/%2…0fae49b8d12195b9624b75a06303984ff883f5b6d345e598b"}
__proto__: Object
loading: undefined
onDocumentComplete: ƒ (pages)
page: 1
scale: 0.5
__proto__: Object
ref: null
type: ƒ ReactPdfJs()
_owner: ReactCompositeComponentWrapper {_currentElement: {…}, _rootNodeID: 0, _compositeType: 0, _instance: PDFViewer, _hostParent: ReactDOMComponent, …}
_store: {validated: true}
_self: null
_source: null
__proto__: Object
```

**Comment by shreyasb07** [comment]
When I see the React Debugger console, i see that the url in the file changes when i select different PDFs, but they don't show up on the canvas somehow! I was wondering why
